### ISSUE TITLE
Error icode.fortran90.rules.COMNAMEHomonymy.run 

### ISSUE THREAD

**Issue by Leobip** [cnescatlab/sonar-icode-cnes-plugin#70]
hi... thanks for the help

I have configured some analyzes and they are giving the errors,  presented in the attached log, apparently due to a rule, which I have deactivated in the profile assigned to the project but it does still fail.

#### Screenshots & log
10:32:54.688 INFO: ------------------------------------------------------------------------
10:32:54 10:32:54.689 INFO: EXECUTION FAILURE
10:32:54 10:32:54.689 INFO: ------------------------------------------------------------------------
10:32:54 10:32:54.689 INFO: Total time: 16.560s
10:32:54 10:32:54.808 INFO: Final Memory: 425M/1773M
10:32:54 10:32:54.808 INFO: ------------------------------------------------------------------------
10:32:54 10:32:54.808 ERROR: Error during SonarScanner execution
10:32:54 java.lang.IndexOutOfBoundsException: Index: -1, Size: 1
10:32:54 	at java.util.LinkedList.checkElementIndex(Unknown Source)
10:32:54 	at java.util.LinkedList.get(Unknown Source)
10:32:54 	at fr.cnes.icode.fortran90.rules.COMNAMEHomonymy.run(COMNAMEHomonymy.java:1477)
10:32:54 	at fr.cnes.icode.Analyzer.stableCheck(Analyzer.java:224)
10:32:54 	at fr.cnes.sonar.plugins.icode.check.ICodeSensor.executeEmbeddedICode(ICodeSensor.java:189)
10:32:54 	at fr.cnes.sonar.plugins.icode.check.ICodeSensor.execute(ICodeSensor.java:110)
10:32:54 	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
10:32:54 	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
10:32:54 	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
10:32:54 	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
10:32:54 	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
10:32:54 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:177)
10:32:54 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
10:32:54 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
10:32:54 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:291)
10:32:54 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:286)
10:32:54 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:264)
10:32:54 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
10:32:54 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
10:32:54 	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
10:32:54 	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
10:32:54 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
10:32:54 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
10:32:54 	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
10:32:54 	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
10:32:54 	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:71)
10:32:54 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
10:32:54 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:32:54 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
10:32:54 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
10:32:54 	at java.lang.reflect.Method.invoke(Unknown Source)
10:32:54 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
10:32:54 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
10:32:54 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
10:32:54 	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
10:32:54 	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
10:32:54 	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
10:32:54 	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
10:32:55 WARN: Unable to locate 'report-task.txt' in the workspace. Did the SonarScanner succeed?
10:32:55 ERROR: SonarQube scanner exited with non-zero code: 1
10:32:58 Finished: FAILURE

#### User environment 
> _Please complete the following information._
 - OS:   SonarQube Linux (Centos)
 - Java version: [1.8.0_91]
 - Plugin version: [e.g. 2.0.1]
- SonarQube: 6.7

**Comment by begarco** [comment]
Hi @Leobip,

Please consider using plugin 2.0.2 which should fix your issue.

Benoît for CatLab

**Comment by Leobip** [comment]
thanks... but the 2.0.2 not work with sonar 6.7 right?

**Comment by begarco** [comment]
It should, on my side it works with LTS version.

**Comment by Leobip** [comment]
Thanks.... i upgraded Java ..and it works
